apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: i2klrv290-python
  janus-idp.io/tekton: i2klrv290-python
  backstage.io/kubernetes-id: i2klrv290-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: i2klrv290-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
